In [2]:
import pandas as pd
rent_hn = pd.read_csv(r"rent_hn.csv")
rent_hs = pd.read_csv(r"rent_hs.csv")

In [3]:
import pandas as pd

# rent_hn과 rent_hs 데이터프레임 병합 (행 단위로)
rent = pd.concat([rent_hn, rent_hs], axis=0, ignore_index=True)

# 결과 확인
rent

,blck_cd,blck_nm,type,pyng,pay_rent,lon,lat
0,C00405,하남풍산1,국민임대,20평 이하,270000,127.200243,37.552468
1,C00406,하남풍산2,국민임대,20평 이하,230000,127.202131,37.551420
2,C00407,하남풍산3,국민임대,20평 이하,270000,127.208378,37.549259
3,C00408,하남풍산4,국민임대,20평 이하,350000,127.208184,37.547167
4,C01801,미사강변도시 A12블록(분납),공공임대,30평 이하,220000,127.188448,37.570743
...,...,...,...,...,...,...,...
154,C02784,화성비봉 A-5블록 행복·영구임대주택,행복주택,20평 이하,170000,126.866536,37.248863
155,C02784,화성비봉 A-5블록 행복·영구임대주택,행복주택,10평 이하,120000,126.866536,37.248863
156,C02784,화성비봉 A-5블록 행복·영구임대주택,영구임대,10평 이하,70000,126.866536,37.248863
157,C02799,화성동탄2 A-54블록 행복주택,행복주택,20평 이하,230000,127.143993,37.185721
158,C02799,화성동탄2 A-54블록 행복주택,행복주택,10평 이하,120000,127.143993,37.185721

In [7]:
import pandas as pd
data = pd.read_excel(r"2021-2023 회귀분석_대시보드.xlsx")
# "공유차량 이용건수" 컬럼 값이 0이 아닌 행만 필터링
filtered_data = data[data["공유차량 이용건수"] != 0]

In [8]:
filtered_data

,year,단지명,sumID,유형별,국민임대,공공임대,영구임대,행복주택,임대료,버스추정교통량,...,pop_20g_pop,pop_30g_pop,pop_40g_pop,pop_50g_pop,pop_60g_pop,pop_70g_pop,pop_80g_pop,pop_90g_pop,pop_100g_pop,공유차량 이용건수
0,2021,화성동탄7-2(1-5)(7단지 능동),Z49,국민임대,1,0,0,0,210000,206621.276000,...,199.000000,196.00000,334.000000,215.000000,167.000000,107.00000,48.00000,6.0,0,366
1,2021,화성동탄5-2(4-6)(5단지 새강),Z50,국민임대,1,0,0,0,200000,169258.299900,...,296.000000,365.00000,618.000000,432.000000,375.000000,236.00000,95.00000,0.0,0,506
2,2021,화성봉담(2단지 동화)(국임),Z38,국민임대,1,0,0,0,160000,52475.337460,...,143.000000,165.00000,311.000000,289.000000,246.000000,160.00000,73.00000,0.0,0,277
3,2021,화성향남(5단지 한우물)(국임),Z28,국민임대,1,0,0,0,80000,72892.167810,...,185.000000,251.00000,373.000000,338.000000,249.000000,76.00000,31.00000,0.0,0,83
4,2021,화성향남(5단지 한우물)(국임),Z28,국민임대,1,0,0,0,170000,72892.167810,...,185.000000,251.00000,373.000000,338.000000,249.000000,76.00000,31.00000,0.0,0,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2023,하남감일 6단지(행복주택)A6블록,Q18,행복주택,0,0,0,1,150000,6426.061190,...,76.000000,479.00000,144.000000,17.000000,29.000000,58.00000,6.00000,0.0,0,552
248,2023,하남감일 6단지(행복주택)A6블록,Q18,행복주택,0,0,0,1,240000,6426.061190,...,76.000000,479.00000,144.000000,17.000000,29.000000,58.00000,6.00000,0.0,0,552
249,2023,"하남감일 8단지(국민, 영구)A3블록",Q19,국민임대,1,0,0,0,160000,3419.430411,...,25.353855,45.07352,40.002749,58.595576,108.176448,84.51285,39.43933,0.0,0,694
250,2023,"하남감일 8단지(국민, 영구)A3블록",Q19,국민임대,1,0,0,0,240000,3419.430411,...,25.353855,45.07352,40.002749,58.595576,108.176448,84.51285,39.43933,0.0,0,694
251,2023,"하남감일 8단지(국민, 영구)A3블록",Q19,영구임대,0,0,1,0,70000,3419.430411,...,19.646145,34.92648,30.997251,45.404424,83.823552,65.48715,30.56067,0.0,0,694

In [9]:
merged_df = pd.merge(
    filtered_data,
    rent[["blck_nm", "lon", "lat"]],  # lon, lat 컬럼만 선택
    left_on="단지명",  # rent_df의 기준 컬럼
    right_on="blck_nm",  # blck_df의 기준 컬럼
    how="left"  # 왼쪽 기준 병합
)
merged_df

,year,단지명,sumID,유형별,국민임대,공공임대,영구임대,행복주택,임대료,버스추정교통량,...,pop_50g_pop,pop_60g_pop,pop_70g_pop,pop_80g_pop,pop_90g_pop,pop_100g_pop,공유차량 이용건수,blck_nm,lon,lat
0,2021,화성동탄7-2(1-5)(7단지 능동),Z49,국민임대,1,0,0,0,210000,206621.276000,...,215.000000,167.000000,107.00000,48.00000,6.0,0,366,화성동탄7-2(1-5)(7단지 능동),127.061128,37.211268
1,2021,화성동탄5-2(4-6)(5단지 새강),Z50,국민임대,1,0,0,0,200000,169258.299900,...,432.000000,375.000000,236.00000,95.00000,0.0,0,506,화성동탄5-2(4-6)(5단지 새강),127.069179,37.193522
2,2021,화성봉담(2단지 동화)(국임),Z38,국민임대,1,0,0,0,160000,52475.337460,...,289.000000,246.000000,160.00000,73.00000,0.0,0,277,화성봉담(2단지 동화)(국임),126.960738,37.218666
3,2021,화성향남(5단지 한우물)(국임),Z28,국민임대,1,0,0,0,80000,72892.167810,...,338.000000,249.000000,76.00000,31.00000,0.0,0,83,화성향남(5단지 한우물)(국임),126.915635,37.124382
4,2021,화성향남(5단지 한우물)(국임),Z28,국민임대,1,0,0,0,80000,72892.167810,...,338.000000,249.000000,76.00000,31.00000,0.0,0,83,화성향남(5단지 한우물)(국임),126.915635,37.124382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,2023,"하남감일 8단지(국민, 영구)A3블록",Q19,국민임대,1,0,0,0,240000,3419.430411,...,58.595576,108.176448,84.51285,39.43933,0.0,0,694,"하남감일 8단지(국민, 영구)A3블록",127.163453,37.511638
465,2023,"하남감일 8단지(국민, 영구)A3블록",Q19,국민임대,1,0,0,0,240000,3419.430411,...,58.595576,108.176448,84.51285,39.43933,0.0,0,694,"하남감일 8단지(국민, 영구)A3블록",127.163453,37.511638
466,2023,"하남감일 8단지(국민, 영구)A3블록",Q19,영구임대,0,0,1,0,70000,3419.430411,...,45.404424,83.823552,65.48715,30.56067,0.0,0,694,"하남감일 8단지(국민, 영구)A3블록",127.163453,37.511638
467,2023,"하남감일 8단지(국민, 영구)A3블록",Q19,영구임대,0,0,1,0,70000,3419.430411,...,45.404424,83.823552,65.48715,30.56067,0.0,0,694,"하남감일 8단지(국민, 영구)A3블록",127.163453,37.511638
468,2023,"하남감일 8단지(국민, 영구)A3블록",Q19,영구임대,0,0,1,0,70000,3419.430411,...,45.404424,83.823552,65.48715,30.56067,0.0,0,694,"하남감일 8단지(국민, 영구)A3블록",127.163453,37.511638

In [10]:
merged_df.to_csv("merged_data.csv", index=False, encoding="utf-8-sig")

In [11]:
merged_df.columns

Index(['year', '단지명', 'sumID', '유형별', '국민임대', '공공임대', '영구임대', '행복주택', '임대료',
       '버스추정교통량', '승용차추정교통량', '대중교통접근성_상', '대중교통접근성_중', '대중교통접근성_하',
       '생활서비스형상권', '소매외식형상권', '이동여가형상권', 'pop_20g_pop', 'pop_30g_pop',
       'pop_40g_pop', 'pop_50g_pop', 'pop_60g_pop', 'pop_70g_pop',
       'pop_80g_pop', 'pop_90g_pop', 'pop_100g_pop', '공유차량 이용건수', 'blck_nm',
       'lon', 'lat'],
      dtype='object')

In [12]:
import joblib

file_path = "./xgboost_model.pkl"
try:
    model = joblib.load(file_path)
    print("모델 로드 성공!")
except ModuleNotFoundError as e:
    print(f"모듈을 찾을 수 없습니다: {e}")

모델 로드 성공!

In [15]:
import sklearn
print(sklearn.__version__)

1.6.0

In [14]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import joblib  # 모델 저장용

# 데이터 준비 (merged_data.csv 예제)
data = pd.read_csv(r"merged_data.csv")

# 독립변수와 종속변수 분리
FEATURE_COLUMNS = ['국민임대', '공공임대', '영구임대', '행복주택', '임대료',
       '버스추정교통량', '승용차추정교통량', '대중교통접근성_상', '대중교통접근성_중', '대중교통접근성_하',
       '생활서비스형상권', '소매외식형상권', '이동여가형상권', 'pop_20g_pop', 'pop_30g_pop',
       'pop_40g_pop', 'pop_50g_pop', 'pop_60g_pop', 'pop_70g_pop',
       'pop_80g_pop', 'pop_90g_pop', 'pop_100g_pop']
TARGET_COLUMN = '공유차량 이용건수'

X = data[FEATURE_COLUMNS]
y = data[TARGET_COLUMN]

# 학습/테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 하이퍼파라미터 그리드 설정
param_grid = {
    'n_estimators': [200],
    'max_depth': [7],
    'learning_rate': [0.1],
    'subsample': [1.0],
    'colsample_bytree': [0.8]
}

# XGBoost 모델 초기화 (param_grid 사용)
model = xgb.XGBRegressor(
    n_estimators=param_grid['n_estimators'][0],
    max_depth=param_grid['max_depth'][0],
    learning_rate=param_grid['learning_rate'][0],
    subsample=param_grid['subsample'][0],
    colsample_bytree=param_grid['colsample_bytree'][0],
    random_state=42  # 고정값
)

# 모델 학습
print("모델 학습을 시작합니다...")
model.fit(X_train, y_train)
print("모델 학습이 완료되었습니다!")

# 테스트 데이터 평가
# print("모델 성능 평가 중...")
# y_pred = model.predict(X_test)
# rmse = mean_squared_error(y_test, y_pred, squared=False)
# mae = mean_absolute_error(y_test, y_pred)
# print(f"테스트 RMSE: {rmse:.4f}")
# print(f"테스트 MAE: {mae:.4f}")

# 모델과 피처 정보 저장
model_data = {
    "model": model,
    "features": FEATURE_COLUMNS
}
joblib.dump(model, "xgboost_model2.pkl")
print(f"모델과 피처 정보가 'xgboost_model2.pkl'에 저장되었습니다.")

모델 학습을 시작합니다...
모델 학습이 완료되었습니다!
모델과 피처 정보가 'xgboost_model2.pkl'에 저장되었습니다.